/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-19 22:35:08 
*/
import { ObjectId } from "bson";
import { IOptionalProperty } from '../../../../common/types/IOptionalProperty';
import { ILinkingObjects } from "../../../../common/types/ILinkingObjects";

export interface IDTOSelfStorage {
    _id: ObjectId;
    name: string;
    website: IOptionalProperty<string>;
    facilities: ILinkingObjects;
}
