/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-21 04:04:20 
*/
import { ObjectId } from "bson";
import { FileLocationObj } from "../../embedded/FileLocation/FileLocationObj";

export interface IDBFileInfo {
    _id: ObjectId;
    id: number;
    createDate?: any;
    data?: any;
    hash?: string;
    ids: any;
    isUnassigned?: boolean;
    itemType?: string;
    location?: FileLocationObj;
    mimeType?: string;
    modifiedDate?: any;
    size?: number;
    type?: string;
}
