/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-21 01:39:41 
*/
import { ObjectId } from "bson";
import { Dictionary } from "realm";

export interface IIdentity {
    ids: Record<string, number> & Dictionary;
    _id: ObjectId;
}
