export const provinceMap = {
    AR: 'Arkansas',
    AK: 'Alaska',
    AL: 'Alabama',
    AZ: 'Arizona',
    CA: 'California',
    CO: 'Colorado',
    CT: 'Connecticut',
    DE: 'Deleware',
    FL: 'Florida',
    GA: 'Georgia',
    HI: 'Hawaii',
    IA: 'Iowa',
    ID: 'Idaho',
    IN: 'Indiana',
    IL: 'Illinois',
    KS: 'Kansas',
    KY: 'Kentucky',
    LA: 'Louisiana',
    MA: 'Massachusettes',
    MI: 'Michigan',
    MN: 'Minnesota',
    MO: 'Missouri',
    MD: 'Maryland',
    ME: 'Maine',
    MS: 'Mississippi',
    MT: 'Montana',
    NE: 'Nebraska',
    NV: 'Nevada',
    NY: 'New York',
    NJ: 'New Jersey',
    NH: 'New Hampshire',
    NM: 'New Mexico',
    OH: 'Ohio',
    OR: 'Oregon',
    OK: 'Oklahoma',
    PA: 'Pennsylvania',
    RI: 'Rhode Island',
    SC: 'South Carolina',
    SD: 'South Dakota',
    NC: 'North Carolina',
    ND: 'North Dakota',
    TN: 'Tennessee',
    TX: 'Texas',
    UT: 'Utah',
    VT: 'Vermont',
    VA: 'Virginia',
    WV: 'West Virginia',
    WY: 'Wyoming',
    WA: 'Washington',
    WI: 'Wisconsin',
    DC: 'District of Columbia',
    PR: 'Puerto Rico',
    AB: 'Alberta',
    ON: 'Ontario',
    QB: 'Quebec',
    NS: 'Nova Scotia',
    NB: 'New Brunswick',
    YT: 'Yukon',
    NT: 'Northwest Territories',
    BC: 'British Columbia',
    SK: 'Saskatchewan',
    MB: 'Manitoba',
    NL: 'Newfoundland and Labrador',
    NU: 'Nunavut',
    PE: 'Prince Edward Island'
};

export type Provinces = keyof typeof provinceMap;