/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-21 03:38:28 
*/
import { ObjectId } from "bson";
import { ObjectSchema } from "realm";
import { Reflector } from "../..";
import { IOptionalProperty } from "../../../../common/types/IOptionalProperty";

export interface IDBAuctionLot {
    _id: ObjectId;
    id: number;
    auctionID: IOptionalProperty<string>;
    auctionSite: Realm.Object;
    cleanout: IOptionalProperty<number>;
    closeDate: Date;
    facility: Realm.Object;
    invoice: Realm.Object;
    size: IOptionalProperty<string>;
    unit: IOptionalProperty<string>;
    unitSize: IOptionalProperty<string>;
}
