import { IEnhNumber } from '../../../common/types/IEnhNumber';

/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-19 04:45:00 
*/
export interface I$dto$cost {
    bid: IEnhNumber;
    depositAmount: IEnhNumber;
    premiumPercent: IEnhNumber;
    salesTaxPercent: IEnhNumber;
    taxExempt: boolean;
    readonly premiumAmount: IEnhNumber;
    readonly salesTaxAmount: IEnhNumber;
    readonly totalAmount: IEnhNumber;
}
