/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-19 05:10:29 
*/

export interface I$dto$file$location {
    drive?: string;
    folder: string;
    filename: string;
}
