/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-21 03:31:50 
*/
import { ObjectId } from "bson";
import { Reflector } from "../..";
import { AddressObj } from "../../embedded/Address/AddressObj";
import { IOptionalProperty } from '../../../../common/types/IOptionalProperty';
import { IDTOSelfStorage } from '../DBSelfStorage/IDTOSelfStorage';

export interface IDTOFacility {
    _id: ObjectId;
    id: number;
    address: AddressObj;
    facilityNumber: IOptionalProperty<string>;
    phoneNumber: IOptionalProperty<string>;
    selfStorage?: IDTOSelfStorage;
}
