/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-21 03:50:53 
*/
import { ObjectId } from "bson";
import { ObjectSchema } from "realm";
import { Reflector } from "../..";

export interface IDBAuctionSite {
    _id: ObjectId;
    id: number;
    name: string;
    website?: string;
}
